/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visaoMaster;

import Beans.BeansContasBancarias;
import Beans.BeansRegistrarMov;
import Beans.BeansTabelas;
import Dao.DaoContasBancarias;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloConection.ConexaoBD;

/**
 *
 * @author Professor
 */
public class CadContasBancarias extends javax.swing.JFrame {
    
    ConexaoBD conex = new ConexaoBD();
    BeansContasBancarias mod = new BeansContasBancarias();
    DaoContasBancarias control = new DaoContasBancarias();
    
    /**
     * Creates new form janelaPadrao
     */
    public CadContasBancarias() {
        initComponents();
        CbCorrentista();
        CbBank();
        PreencherTabela("SELECT a.id_contbank, b.nomebank, a.tipocard, a.nuncard FROM tbl_contbank as a inner join tbl_bank as b on (a.id_bank = b. id_bank) order by id_contbank");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonIncluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonApagar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonImprimir = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jTextFieldCod = new javax.swing.JTextField();
        jLabelCod = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelFaixaMenu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxCorrentista = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxTconta = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNomeCartao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxTcatao = new javax.swing.JComboBox<>();
        jLabelAgCont = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jDateChooserVnc = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCvv = new javax.swing.JTextField();
        jLabelNuncard = new javax.swing.JLabel();
        jTextFieldNumCartao = new javax.swing.JTextField();
        jTextFieldAgenCont = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxBanco = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jButtonIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/incluir.png"))); // NOI18N
        jButtonIncluir.setToolTipText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIncluir);
        jButtonIncluir.setBounds(10, 0, 45, 30);

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/salvar.png"))); // NOI18N
        jButtonEditar.setToolTipText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar);
        jButtonEditar.setBounds(60, 0, 45, 30);

        jButtonApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/apagar.png"))); // NOI18N
        jButtonApagar.setToolTipText("Deletar");
        jButtonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonApagar);
        jButtonApagar.setBounds(110, 0, 45, 30);

        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/limpar.png"))); // NOI18N
        jButtonLimpar.setToolTipText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpar);
        jButtonLimpar.setBounds(160, 0, 45, 30);

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/pesquisar.png"))); // NOI18N
        jButtonPesquisar.setToolTipText("Buscar");
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(210, 0, 45, 30);

        jButtonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/imprimir.png"))); // NOI18N
        jButtonImprimir.setToolTipText("Imprimir");
        getContentPane().add(jButtonImprimir);
        jButtonImprimir.setBounds(260, 0, 45, 30);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/sair.png"))); // NOI18N
        jButtonSair.setToolTipText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(310, 0, 45, 30);

        jTextFieldCod.setEditable(false);
        jTextFieldCod.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextFieldCod);
        jTextFieldCod.setBounds(460, 30, 59, 25);

        jLabelCod.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelCod.setText("Cod.:");
        getContentPane().add(jLabelCod);
        jLabelCod.setBounds(420, 30, 40, 25);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("* Campos de preenchimento obrigatório.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 430, 220, 14);

        jLabelFaixaMenu.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFaixaMenu.setForeground(new java.awt.Color(102, 255, 255));
        jLabelFaixaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_Faixa.png"))); // NOI18N
        getContentPane().add(jLabelFaixaMenu);
        jLabelFaixaMenu.setBounds(0, 0, 540, 30);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Correntista:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 50, 80, 25);

        jComboBoxCorrentista.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxCorrentista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBoxCorrentista);
        jComboBoxCorrentista.setBounds(90, 50, 280, 25);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Tipo de Conta:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 80, 90, 25);

        jComboBoxTconta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxTconta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CORRENTE", "POUPANÇA", "CORRENTE / POUPANÇA", "NÃO CORRENTISTA" }));
        getContentPane().add(jComboBoxTconta);
        jComboBoxTconta.setBounds(90, 80, 280, 25);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Vincular Catão"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nome Impresso no Cartão:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 150, 25));

        jTextFieldNomeCartao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(jTextFieldNomeCartao, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 240, 25));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Tipo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 40, 25));

        jComboBoxTcatao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxTcatao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DÉBITO", "CRÉDITO" }));
        jComboBoxTcatao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTcataoItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBoxTcatao, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 240, 25));

        jLabelAgCont.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAgCont.setText("Agência / Conta:");
        jPanel1.add(jLabelAgCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 130, 25));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Vencimento do Cartão:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 140, 25));

        jDateChooserVnc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(jDateChooserVnc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 150, 25));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("CVV:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 50, 25));

        jTextFieldCvv.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(jTextFieldCvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 60, 25));

        jLabelNuncard.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNuncard.setText(" Número do Cartão:");
        jPanel1.add(jLabelNuncard, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 120, 25));

        jTextFieldNumCartao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextFieldNumCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumCartaoActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldNumCartao, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 240, 25));

        jTextFieldAgenCont.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(jTextFieldAgenCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 240, 25));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 150, 510, 210);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Banco:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 110, 70, 25);

        jComboBoxBanco.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxBanco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BANCO DO BRASIL", "BANCO REAL", "BRADESCO", "CAIXA", "ITAÚ", "SANTANDER", "OUTROS" }));
        getContentPane().add(jComboBoxBanco);
        jComboBoxBanco.setBounds(90, 110, 280, 25);

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 360, 510, 70);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_fundo.png"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 30, 580, 460);

        setSize(new java.awt.Dimension(537, 488));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed

        TbCadastros cad = new TbCadastros();
        cad.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed

        
        
        
        jTextFieldNomeCartao.setText("");
        jTextFieldNumCartao.setText("");
        jTextFieldAgenCont.setText("");
        jDateChooserVnc.setDate(null);
        jTextFieldCvv.setText("");
        
        jButtonIncluir.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonApagar.setEnabled(false);
        
    }//GEN-LAST:event_jButtonLimparActionPerformed
    

    
    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        
        if(jTextFieldNomeCartao.getText().isEmpty() || jTextFieldNumCartao.getText().isEmpty() || jDateChooserVnc.getDate() == null || jTextFieldCvv.getText().isEmpty() ){
        if(jTextFieldCvv.getText().isEmpty()){
            jTextFieldCvv.requestFocus();
        }
        if(jDateChooserVnc.getDate() == null){
            jDateChooserVnc.requestFocusInWindow();
        }
        if(jTextFieldNumCartao.getText().isEmpty()){
            jTextFieldNumCartao.requestFocus();
        }
        
        if(jTextFieldNomeCartao.getText().isEmpty()){
            jTextFieldNomeCartao.requestFocus();
        }

        }else{

        mod.setCorrentista((String) jComboBoxCorrentista.getSelectedItem());
        mod.setTipodeconta((String) jComboBoxTconta.getSelectedItem());
        mod.setBanco((String) jComboBoxBanco.getSelectedItem());
        mod.setTcard((String) jComboBoxTcatao.getSelectedItem());
        mod.setNomecard(jTextFieldNomeCartao.getText());
        mod.setNumcard(jTextFieldNumCartao.getText());
        mod.setAgencont(jTextFieldAgenCont.getText());
        mod.setVenccarad(jDateChooserVnc.getDate());
        mod.setCvvcard(jTextFieldCvv.getText());
        control.Salvar(mod);
        jButtonIncluir.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonApagar.setEnabled(true);
        
        }
          
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarActionPerformed
        jButtonEditar.setEnabled(false);
        jButtonApagar.setEnabled(false);
        jButtonIncluir.setEnabled(true);
    }//GEN-LAST:event_jButtonApagarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        if(jTextFieldNomeCartao.getText().isEmpty() || jTextFieldNumCartao.getText().isEmpty() || jDateChooserVnc.getDate() == null || jTextFieldCvv.getText().isEmpty() ){
        if(jTextFieldCvv.getText().isEmpty()){
            jTextFieldCvv.requestFocus();
        }
        if(jDateChooserVnc.getDate() == null){
            jDateChooserVnc.requestFocusInWindow();
        }
        if(jTextFieldNumCartao.getText().isEmpty()){
            jTextFieldNumCartao.requestFocus();
        }
        
        if(jTextFieldNomeCartao.getText().isEmpty()){
            jTextFieldNomeCartao.requestFocus();
        }

        }else{

        mod.setCorrentista((String) jComboBoxCorrentista.getSelectedItem());
        mod.setTipodeconta((String) jComboBoxTconta.getSelectedItem());
        mod.setBanco((String) jComboBoxBanco.getSelectedItem());
        mod.setTcard((String) jComboBoxTcatao.getSelectedItem());
        mod.setNomecard(jTextFieldNomeCartao.getText());
        mod.setNumcard(jTextFieldNumCartao.getText());
        mod.setVenccarad(jDateChooserVnc.getDate());
        mod.setCvvcard(jTextFieldCvv.getText());
        control.Editar(mod);
        jButtonIncluir.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonApagar.setEnabled(true);
        
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jComboBoxTcataoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTcataoItemStateChanged
        if(jComboBoxTcatao.getSelectedItem().equals("CRÉDITO")){
            jTextFieldAgenCont.setEnabled(false);    
        }else{
            jTextFieldAgenCont.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBoxTcataoItemStateChanged

    private void jTextFieldNumCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumCartaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumCartaoActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        String cod = ""+jTable1.getValueAt(jTable1.getSelectedRow(), 0);

        int i = Integer.parseInt(cod);
        
        mod.setCod(i); 
        BeansContasBancarias model = control.Pesquisar(mod);
        //control.PesquisarReg(mod);
        
         jTextFieldCod.setText(String.valueOf(model.getCod()));
         jComboBoxTconta.setSelectedItem(model.getTipodeconta());
         jComboBoxCorrentista.setSelectedItem(model.getCorrentista());
         jComboBoxBanco.setSelectedItem(model.getBanco());
         jComboBoxTcatao.setSelectedItem(model.getTcard());
         jTextFieldNomeCartao.setText(model.getNomecard());
         jTextFieldNumCartao.setText(model.getNumcard());
         jTextFieldAgenCont.setText(model.getAgencont());
         jDateChooserVnc.setDate(model.getVenccarad());
         jTextFieldCvv.setText(model.getCvvcard());
            
            
        jButtonIncluir.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonApagar.setEnabled(true);   
    }//GEN-LAST:event_jTable1MouseClicked

    public void CbCorrentista(){
    
        conex.conexao();
        conex.executaSql("select *from tbl_corretista where status=true order by nomecorretista");
        try{
            conex.rs.first();
            jComboBoxCorrentista.removeAllItems();
            do{
                jComboBoxCorrentista.addItem(conex.rs.getString("nomecorretista").toUpperCase());
            }while(conex.rs.next());
        
        
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Registre os correntistas  no menu Cadastro de Correntista");
            //RegistrarAtiv.this.dispose();
            }
        }
    
    public void CbBank(){
    
        conex.conexao();
        conex.executaSql("select * from tbl_bank");
        try{
            conex.rs.first();
            jComboBoxBanco.removeAllItems();
            do{
                jComboBoxBanco.addItem(conex.rs.getString("nomebank").toUpperCase());
            }while(conex.rs.next());
        
        
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Entre em contato com o desenvolvedor do sistema!\n"+ex);
            //RegistrarAtiv.this.dispose();
            }
        }
    
    public void PreencherTabela(String SQL){
      ArrayList dados = new ArrayList();
      String[] colunas = new String[]{"","","",""};
      
      conex.conexao();
      conex.executaSql(SQL);

      try{
          conex.rs.first();       
          do{
              dados.add(new Object[]{conex.rs.getInt("id_contbank"),
                                     conex.rs.getString("nomebank"),
                                     conex.rs.getString("tipocard"),                                     
                                     conex.rs.getString("nuncard"),
                                     
                                    });
 
          }while(conex.rs.next());
      
        }catch(SQLException ex){
 
           // JOptionPane.showMessageDialog(rootPane, "Não foram encontrados registros para os filtros selecionados!\nSelecione opção válida");
            
          //JOptionPane.showMessageDialog(rootPane, "Erro ao preencher ArrayList\nErro:"+ex); 
        }
      
      BeansTabelas modelo = new BeansTabelas(dados, colunas);
      
      jTable1.setModel(modelo);
      jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
      jTable1.getColumnModel().getColumn(0).setResizable(false);
      jTable1.getColumnModel().getColumn(0).setHeaderValue("ID");
      jTable1.getColumnModel().getColumn(1).setPreferredWidth(120);
      jTable1.getColumnModel().getColumn(1).setResizable(false);
      jTable1.getColumnModel().getColumn(1).setHeaderValue("BANCO");
      jTable1.getColumnModel().getColumn(2).setPreferredWidth(146);
      jTable1.getColumnModel().getColumn(2).setResizable(false); //não redimensionaveL
      jTable1.getColumnModel().getColumn(2).setHeaderValue("TIPO");
      jTable1.getColumnModel().getColumn(3).setPreferredWidth(197);
      jTable1.getColumnModel().getColumn(3).setResizable(false);
      jTable1.getColumnModel().getColumn(3).setHeaderValue("NÚMERO");
      

      jTable1.getTableHeader().setReorderingAllowed(false); //não reordenavel
      //jTable1.setAutoResizeMode(jTable1.AUTO_RESIZE_OFF); //não redmencionar
      jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//selicioar um dado por vez
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPadrao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonApagar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JComboBox<String> jComboBoxBanco;
    private javax.swing.JComboBox<String> jComboBoxCorrentista;
    private javax.swing.JComboBox<String> jComboBoxTcatao;
    private javax.swing.JComboBox<String> jComboBoxTconta;
    private com.toedter.calendar.JDateChooser jDateChooserVnc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAgCont;
    private javax.swing.JLabel jLabelCod;
    private javax.swing.JLabel jLabelFaixaMenu;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelNuncard;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldAgenCont;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldCvv;
    private javax.swing.JTextField jTextFieldNomeCartao;
    private javax.swing.JTextField jTextFieldNumCartao;
    // End of variables declaration//GEN-END:variables
}
