/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visaoMaster;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import Beans.BeansCadUsuarios;
import Beans.BeansTabelas;
import Dao.DaoCadUsuarios;
import modeloConection.ConexaoBD;

import controller.UpperCase;

public class CadUsuarios extends javax.swing.JFrame {

    BeansCadUsuarios mod = new BeansCadUsuarios();
    DaoCadUsuarios control = new DaoCadUsuarios();
    ConexaoBD conex = new ConexaoBD();
    
    
    public CadUsuarios() {
        initComponents();
        
        
        jButtonImprimir.setEnabled(false);
        jButtonApagar.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jLabelSenhaObg.setVisible(false);
        jLabelLoginObg.setVisible(false);
        jLabelNomeObg.setVisible(false);
        jTextFieldNome.setDocument(new UpperCase());
        jInternalFrameBuscaUsuario.setVisible(false);
        jTextFieldSenhaRev.setText("");
        jLabelMostSenha.setVisible(false);
        jButtonRevelaSenha.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameBuscaUsuario = new javax.swing.JInternalFrame();
        jScrollPaneVeiculo = new javax.swing.JScrollPane();
        jTableUsuario = new javax.swing.JTable();
        jButtonSairIF = new javax.swing.JButton();
        jButtonPesquisarIF = new javax.swing.JButton();
        jLabelFaixaMenu1 = new javax.swing.JLabel();
        JlabelFundoMenuIF = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldCod = new javax.swing.JTextField();
        jLabelCod = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jTextFielEmail = new javax.swing.JTextField();
        jLabelCel = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jLabelLogin = new javax.swing.JLabel();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jTextFieldSenhaRev = new javax.swing.JTextField();
        jTextFieldLogin = new javax.swing.JTextField();
        jFormattedTextFieldCel = new javax.swing.JFormattedTextField();
        jLabelPerfil = new javax.swing.JLabel();
        jComboBoxPerfil = new javax.swing.JComboBox();
        jCheckBoxUserAtivar = new javax.swing.JCheckBox();
        jLabelNomeObg = new javax.swing.JLabel();
        jLabelLoginObg = new javax.swing.JLabel();
        jLabelSenhaObg = new javax.swing.JLabel();
        jButtonRevelaSenha = new javax.swing.JButton();
        jLabelMostSenha = new javax.swing.JLabel();
        jButtonIncluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonApagar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonImprimir = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelFaixaMenu = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Usuários");
        setResizable(false);
        getContentPane().setLayout(null);

        jInternalFrameBuscaUsuario.setTitle("Selecionar Usuário");
        jInternalFrameBuscaUsuario.setVisible(true);
        jInternalFrameBuscaUsuario.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPaneVeiculo.setBackground(new java.awt.Color(255, 255, 255));

        jTableUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableUsuario.setGridColor(new java.awt.Color(255, 255, 255));
        jTableUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUsuarioMouseClicked(evt);
            }
        });
        jScrollPaneVeiculo.setViewportView(jTableUsuario);

        jInternalFrameBuscaUsuario.getContentPane().add(jScrollPaneVeiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 440, 180));

        jButtonSairIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/sair.png"))); // NOI18N
        jButtonSairIF.setToolTipText("Sair");
        jButtonSairIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairIFActionPerformed(evt);
            }
        });
        jInternalFrameBuscaUsuario.getContentPane().add(jButtonSairIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 45, 30));

        jButtonPesquisarIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/pesquisar.png"))); // NOI18N
        jButtonPesquisarIF.setToolTipText("Buscar");
        jButtonPesquisarIF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarIFActionPerformed(evt);
            }
        });
        jInternalFrameBuscaUsuario.getContentPane().add(jButtonPesquisarIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 45, 30));

        jLabelFaixaMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFaixaMenu1.setForeground(new java.awt.Color(102, 255, 255));
        jLabelFaixaMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_Faixa.png"))); // NOI18N
        jInternalFrameBuscaUsuario.getContentPane().add(jLabelFaixaMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 30));

        JlabelFundoMenuIF.setBackground(new java.awt.Color(255, 255, 255));
        JlabelFundoMenuIF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_fundo.png"))); // NOI18N
        JlabelFundoMenuIF.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jInternalFrameBuscaUsuario.getContentPane().add(JlabelFundoMenuIF, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 10, 560, 230));

        getContentPane().add(jInternalFrameBuscaUsuario);
        jInternalFrameBuscaUsuario.setBounds(10, 50, 450, 250);

        jTextFieldNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextFieldNome);
        jTextFieldNome.setBounds(60, 70, 270, 25);

        jLabelNome.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelNome.setText("Nome:");
        getContentPane().add(jLabelNome);
        jLabelNome.setBounds(10, 70, 40, 25);

        jTextFieldCod.setEditable(false);
        jTextFieldCod.setEnabled(false);
        jTextFieldCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCod);
        jTextFieldCod.setBounds(60, 40, 60, 25);

        jLabelCod.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelCod.setText("Código:");
        getContentPane().add(jLabelCod);
        jLabelCod.setBounds(0, 40, 50, 25);

        jLabelEmail.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelEmail.setText("E-mail:");
        getContentPane().add(jLabelEmail);
        jLabelEmail.setBounds(0, 160, 50, 25);

        jTextFielEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextFielEmail);
        jTextFielEmail.setBounds(60, 160, 270, 25);

        jLabelCel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelCel.setText("Celular:");
        getContentPane().add(jLabelCel);
        jLabelCel.setBounds(0, 220, 50, 25);

        jLabelSenha.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelSenha.setText("Senha:");
        getContentPane().add(jLabelSenha);
        jLabelSenha.setBounds(0, 130, 50, 25);

        jLabelLogin.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelLogin.setText("Login:");
        getContentPane().add(jLabelLogin);
        jLabelLogin.setBounds(0, 100, 50, 25);

        jPasswordFieldSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(60, 130, 130, 25);

        jTextFieldSenhaRev.setEditable(false);
        jTextFieldSenhaRev.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldSenhaRev.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldSenhaRev.setForeground(new java.awt.Color(0, 0, 255));
        jTextFieldSenhaRev.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldSenhaRev.setBorder(null);
        getContentPane().add(jTextFieldSenhaRev);
        jTextFieldSenhaRev.setBounds(320, 130, 100, 25);

        jTextFieldLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextFieldLogin);
        jTextFieldLogin.setBounds(60, 100, 270, 25);

        try {
            jFormattedTextFieldCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jFormattedTextFieldCel);
        jFormattedTextFieldCel.setBounds(60, 220, 130, 25);

        jLabelPerfil.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelPerfil.setText("Perfil:");
        getContentPane().add(jLabelPerfil);
        jLabelPerfil.setBounds(0, 190, 50, 25);

        jComboBoxPerfil.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jComboBoxPerfil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "USUARIO", "ADMINISTRADOR" }));
        getContentPane().add(jComboBoxPerfil);
        jComboBoxPerfil.setBounds(60, 190, 240, 25);

        jCheckBoxUserAtivar.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxUserAtivar.setText("Ativo?");
        getContentPane().add(jCheckBoxUserAtivar);
        jCheckBoxUserAtivar.setBounds(270, 40, 55, 23);

        jLabelNomeObg.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelNomeObg.setForeground(new java.awt.Color(255, 0, 0));
        jLabelNomeObg.setText("Obrigatório");
        getContentPane().add(jLabelNomeObg);
        jLabelNomeObg.setBounds(330, 73, 60, 20);

        jLabelLoginObg.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelLoginObg.setForeground(new java.awt.Color(255, 0, 0));
        jLabelLoginObg.setText("Obrigatório");
        getContentPane().add(jLabelLoginObg);
        jLabelLoginObg.setBounds(330, 100, 60, 20);

        jLabelSenhaObg.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelSenhaObg.setForeground(new java.awt.Color(255, 0, 0));
        jLabelSenhaObg.setText("Obrigatório");
        getContentPane().add(jLabelSenhaObg);
        jLabelSenhaObg.setBounds(190, 130, 60, 20);

        jButtonRevelaSenha.setText("Revelar");
        jButtonRevelaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRevelaSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRevelaSenha);
        jButtonRevelaSenha.setBounds(190, 130, 70, 23);

        jLabelMostSenha.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelMostSenha.setForeground(new java.awt.Color(0, 0, 255));
        jLabelMostSenha.setText("Senha:");
        getContentPane().add(jLabelMostSenha);
        jLabelMostSenha.setBounds(270, 130, 60, 25);

        jButtonIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/incluir.png"))); // NOI18N
        jButtonIncluir.setToolTipText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIncluir);
        jButtonIncluir.setBounds(10, 0, 45, 30);

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/salvar.png"))); // NOI18N
        jButtonEditar.setToolTipText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar);
        jButtonEditar.setBounds(60, 0, 45, 30);

        jButtonApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/apagar.png"))); // NOI18N
        jButtonApagar.setToolTipText("Deletar");
        jButtonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonApagar);
        jButtonApagar.setBounds(110, 0, 45, 30);

        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/limpar.png"))); // NOI18N
        jButtonLimpar.setToolTipText("Limpar");
        jButtonLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLimparMouseClicked(evt);
            }
        });
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpar);
        jButtonLimpar.setBounds(160, 0, 45, 30);

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/pesquisar.png"))); // NOI18N
        jButtonPesquisar.setToolTipText("Buscar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(210, 0, 45, 30);

        jButtonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/imprimir.png"))); // NOI18N
        jButtonImprimir.setToolTipText("Imprimir");
        getContentPane().add(jButtonImprimir);
        jButtonImprimir.setBounds(260, 0, 45, 30);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/sair.png"))); // NOI18N
        jButtonSair.setToolTipText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(310, 0, 45, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("* Campos de preenchimento obrigatório.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 250, 220, 14);

        jLabelFaixaMenu.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFaixaMenu.setForeground(new java.awt.Color(102, 255, 255));
        jLabelFaixaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_Faixa.png"))); // NOI18N
        getContentPane().add(jLabelFaixaMenu);
        jLabelFaixaMenu.setBounds(0, 0, 500, 30);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_fundo.png"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 30, 520, 320);

        setSize(new java.awt.Dimension(493, 303));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        TbPanelControl panelcontrol = new TbPanelControl();
        panelcontrol.setVisible(true);
        dispose();        
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLimparMouseClicked
        jTextFieldCod.setText("");
        jTextFieldNome.setText("");
        jTextFielEmail.setText("");
        jTextFieldLogin.setText("");
        jFormattedTextFieldCel.setText("");
        jPasswordFieldSenha.setText("");
        jTextFieldSenhaRev.setText("");
        jLabelMostSenha.setVisible(false);
        jButtonRevelaSenha.setVisible(false);
        jCheckBoxUserAtivar.setSelected(false);
        jButtonIncluir.setEnabled(true);
        jButtonApagar.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jLabelSenhaObg.setVisible(false);
        jLabelLoginObg.setVisible(false);
        jLabelNomeObg.setVisible(false);
    
    }//GEN-LAST:event_jButtonLimparMouseClicked

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
       
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jTextFieldCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodActionPerformed

    }//GEN-LAST:event_jTextFieldCodActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        
     if(jTextFieldNome.getText().isEmpty()|| jTextFieldLogin.getText().isEmpty() || jPasswordFieldSenha.getText().isEmpty()) { 
 
            if(jTextFieldNome.getText().isEmpty()){ 
            jLabelNomeObg.setVisible(true);
            //JOptionPane.showMessageDialog(null, "Campo Obrigatório");
            jTextFieldNome.requestFocus();  
            }else{
            jLabelNomeObg.setVisible(false);
            }
            if(jTextFieldLogin.getText().isEmpty()) { 
            jLabelLoginObg.setVisible(true);
            //JOptionPane.showMessageDialog(null, "Campo Obrigatório");
            jTextFieldLogin.requestFocus(); 
            }else{
            jLabelLoginObg.setVisible(false);
            }
            if(jPasswordFieldSenha.getText().isEmpty()) { 
            jLabelSenhaObg.setVisible(true);
            jPasswordFieldSenha.requestFocus();  
            //JOptionPane.showMessageDialog(null, "Campo Obrigatório");
            }else{
            jLabelSenhaObg.setVisible(false);    
            }        
        }else{
            mod.setNome(jTextFieldNome.getText());
            mod.setLogin(jTextFieldLogin.getText());
            mod.setSenha(jPasswordFieldSenha.getText());
            mod.setEmail(jTextFielEmail.getText());
            mod.setPerfil((String) jComboBoxPerfil.getSelectedItem()); 
            mod.setCelular(jFormattedTextFieldCel.getText());
            mod.setAtivo(jCheckBoxUserAtivar.isSelected());
            control.Editar(mod);
            jLabelSenhaObg.setVisible(false);
            jLabelLoginObg.setVisible(false);
            jLabelNomeObg.setVisible(false); 
            jButtonIncluir.setEnabled(false);
            jButtonApagar.setEnabled(true);
            jButtonEditar.setEnabled(true);
            jTextFieldSenhaRev.setText("");
        jButtonRevelaSenha.setVisible(true);
        jLabelMostSenha.setVisible(false);
        }   
        
       
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarActionPerformed
        
            int Confirm = JOptionPane.showConfirmDialog(null,"Excluir registro?"," Excluir", JOptionPane.YES_NO_OPTION);
            if (Confirm == JOptionPane.YES_OPTION) {
            mod.setCodigo(Integer.parseInt(jTextFieldCod.getText()));
            mod.setNome(jTextFieldNome.getText());
            control.Excluir(mod);
            
            jTextFieldCod.setText("");
            jTextFieldNome.setText("");
            jTextFielEmail.setText("");
            jTextFieldLogin.setText("");
            jFormattedTextFieldCel.setText("");
            jPasswordFieldSenha.setText("");
            jCheckBoxUserAtivar.setSelected(false);
            jButtonIncluir.setEnabled(true);
            jButtonApagar.setEnabled(false);
            jButtonEditar.setEnabled(false);
            jTextFieldSenhaRev.setText("");
            jButtonRevelaSenha.setVisible(false);
            jLabelMostSenha.setVisible(false);
            
            }else if (Confirm == JOptionPane.NO_OPTION){
                setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            }
     
        

    }//GEN-LAST:event_jButtonApagarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
         
         PreencherTabelaIF("select id_usuario,nome,usuario,perfil from tbl_usuarios");
         jInternalFrameBuscaUsuario.setVisible(true);
       
        
        jLabelNomeObg.setVisible(false);
        jButtonIncluir.setEnabled(false);
        jButtonApagar.setEnabled(true);
        jButtonEditar.setEnabled(true);
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        if(jTextFieldNome.getText().isEmpty()|| jTextFieldLogin.getText().isEmpty() || jPasswordFieldSenha.getText().isEmpty()) { 
 
            if(jTextFieldNome.getText().isEmpty()){ 
            jLabelNomeObg.setVisible(true);
            //JOptionPane.showMessageDialog(null, "Campo Obrigatório");
            jTextFieldNome.requestFocus();  
            }else{
            jLabelNomeObg.setVisible(false);
            }
            if(jTextFieldLogin.getText().isEmpty()) { 
            jLabelLoginObg.setVisible(true);
            //JOptionPane.showMessageDialog(null, "Campo Obrigatório");
            jTextFieldLogin.requestFocus(); 
            }else{
            jLabelLoginObg.setVisible(false);
            }
            if(jPasswordFieldSenha.getText().isEmpty()) { 
            jLabelSenhaObg.setVisible(true);
            jPasswordFieldSenha.requestFocus();  
            //JOptionPane.showMessageDialog(null, "Campo Obrigatório");
            }else{
            jLabelSenhaObg.setVisible(false);    
            }        
        }else{
            mod.setNome(jTextFieldNome.getText());
            mod.setLogin(jTextFieldLogin.getText());
            mod.setSenha(jPasswordFieldSenha.getText());
            mod.setEmail(jTextFielEmail.getText());
            mod.setPerfil((String) jComboBoxPerfil.getSelectedItem()); 
            mod.setCelular(jFormattedTextFieldCel.getText());
            mod.setAtivo(jCheckBoxUserAtivar.isSelected());
            control.Salvar(mod);
            
            
            BeansCadUsuarios model = control.Pesquisar(mod);
            jTextFieldCod.setText(String.valueOf(model.getCodigo()));
            
            jTextFieldSenhaRev.setText("");
            jButtonRevelaSenha.setVisible(false);
            jLabelSenhaObg.setVisible(false);
            jLabelLoginObg.setVisible(false);
            jLabelNomeObg.setVisible(false); 
            jButtonIncluir.setEnabled(false);
            jButtonEditar.setEnabled(true);
            jButtonApagar.setEnabled(true);
            jButtonRevelaSenha.setVisible(true);
        }
   
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jPasswordFieldSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaActionPerformed
       
    }//GEN-LAST:event_jPasswordFieldSenhaActionPerformed

    private void jTableUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsuarioMouseClicked
        String login = ""+jTableUsuario.getValueAt(jTableUsuario.getSelectedRow(), 2);

            mod.setLogin(login);
            BeansCadUsuarios model = control.Pesquisar(mod);
            jTextFieldCod.setText(String.valueOf(model.getCodigo()));
            jTextFieldNome.setText(model.getNome());
            jTextFieldLogin.setText(model.getLogin());
            jPasswordFieldSenha.setText(model.getSenha());
            jTextFielEmail.setText(model.getEmail());
            jComboBoxPerfil.setSelectedItem(model.getPerfil());
            jFormattedTextFieldCel.setText(model.getCelular());
            jCheckBoxUserAtivar.setSelected(model.isAtivo());

        jInternalFrameBuscaUsuario.setVisible(false);
        jTextFieldSenhaRev.setText("");
        jButtonRevelaSenha.setVisible(true);
        jLabelMostSenha.setVisible(false);
        
        jButtonIncluir.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonApagar.setEnabled(true);

    }//GEN-LAST:event_jTableUsuarioMouseClicked

    private void jButtonSairIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairIFActionPerformed
        jInternalFrameBuscaUsuario.dispose();
    }//GEN-LAST:event_jButtonSairIFActionPerformed

    private void jButtonPesquisarIFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarIFActionPerformed
        PreencherTabelaIF("select id_usuario,nome,usuario,perfil from tbl_usuarios");
    }//GEN-LAST:event_jButtonPesquisarIFActionPerformed

    private void jButtonRevelaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRevelaSenhaActionPerformed
        mod.setNome(jTextFieldNome.getText());
        BeansCadUsuarios model = control.RevelaPassword(mod);
        jLabelMostSenha.setVisible(true);
        jTextFieldSenhaRev.setText(model.getSenha());
        
    }//GEN-LAST:event_jButtonRevelaSenhaActionPerformed

public void PreencherTabelaIF(String SQL){
      ArrayList dados = new ArrayList();
      String[] colunas = new String[]{"COD","PLACA","MODELO","STATUS"};
      
      conex.conexao();
      conex.executaSql(SQL);

      try{
          conex.rs.first();       
          do{
              dados.add(new Object[]{conex.rs.getInt("id_usuario"),
                                     conex.rs.getString("nome"),
                                     conex.rs.getString("usuario"),
                                     conex.rs.getString("perfil")
                                   
                                    });
 
          }while(conex.rs.next());
      
        }catch(SQLException ex){
          JOptionPane.showMessageDialog(null, "Erro ao preencher ArrayList\nErro:"+ex);
        }
          
     BeansTabelas modelo = new BeansTabelas(dados, colunas);
      
     jTableUsuario.setModel(modelo);
     jTableUsuario.getColumnModel().getColumn(0).setPreferredWidth(40);
     jTableUsuario.getColumnModel().getColumn(0).setResizable(false);
     jTableUsuario.getColumnModel().getColumn(0).setHeaderValue("COD");
     jTableUsuario.getColumnModel().getColumn(1).setPreferredWidth(181);
     jTableUsuario.getColumnModel().getColumn(1).setResizable(false); //não redimensionaveL
     jTableUsuario.getColumnModel().getColumn(1).setHeaderValue("NOME");
     jTableUsuario.getColumnModel().getColumn(2).setPreferredWidth(80);
     jTableUsuario.getColumnModel().getColumn(2).setResizable(false); //não redimensionaveL
     jTableUsuario.getColumnModel().getColumn(2).setHeaderValue("LOGIN");
     jTableUsuario.getColumnModel().getColumn(3).setPreferredWidth(115);
     jTableUsuario.getColumnModel().getColumn(3).setResizable(false); //não redimensionaveL
     jTableUsuario.getColumnModel().getColumn(3).setHeaderValue("PERFIL");
           

     jTableUsuario.getTableHeader().setReorderingAllowed(false); //não reordenavel
     jTableUsuario.setAutoResizeMode(jTableUsuario.AUTO_RESIZE_OFF); //não redmencionar
     jTableUsuario.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//selicioar um dado por vez
    }



    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPadrao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlabelFundoMenuIF;
    private javax.swing.JButton jButtonApagar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonPesquisarIF;
    private javax.swing.JButton jButtonRevelaSenha;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSairIF;
    private javax.swing.JCheckBox jCheckBoxUserAtivar;
    private javax.swing.JComboBox jComboBoxPerfil;
    private javax.swing.JFormattedTextField jFormattedTextFieldCel;
    private javax.swing.JInternalFrame jInternalFrameBuscaUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCel;
    private javax.swing.JLabel jLabelCod;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFaixaMenu;
    private javax.swing.JLabel jLabelFaixaMenu1;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelLoginObg;
    private javax.swing.JLabel jLabelMostSenha;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNomeObg;
    private javax.swing.JLabel jLabelPerfil;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelSenhaObg;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JScrollPane jScrollPaneVeiculo;
    private javax.swing.JTable jTableUsuario;
    private javax.swing.JTextField jTextFielEmail;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldSenhaRev;
    // End of variables declaration//GEN-END:variables
}
