/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visaoMaster;

//import visaoUsuario.MenuPrincipal;
import modeloConection.ConexaoBD;
import Beans.BeansLogin;
import Dao.DaoLogin;

/**
 *
 * @author Professor
 */
public class Login extends javax.swing.JFrame {
    
    ConexaoBD conex = new ConexaoBD();
    BeansLogin mod = new BeansLogin();
    DaoLogin control = new DaoLogin();
    
 
    
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelNameSetor = new javax.swing.JLabel();
        jLabelFaixaInfeior = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelLogin = new javax.swing.JLabel();
        jLabelfundoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Portal de Sistemas");
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PORTAL DE SISTEMAS DE GESTÃO PESSOAL");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 110, 280, 20);

        jTextFieldUser.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextFieldUser.setForeground(new java.awt.Color(255, 102, 51));
        jTextFieldUser.setText("jsilva");
        jTextFieldUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUser);
        jTextFieldUser.setBounds(250, 170, 280, 30);

        jPasswordFieldSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(250, 230, 280, 30);

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 102, 51));
        jLabelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelUsuario.setText("INTRANET");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(350, 410, 80, 20);

        jLabelNameSetor.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabelNameSetor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNameSetor.setText("Todos os direitos reservados a Joelson Souza");
        getContentPane().add(jLabelNameSetor);
        jLabelNameSetor.setBounds(530, 430, 310, 30);

        jLabelFaixaInfeior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_FaixaInferior.png"))); // NOI18N
        getContentPane().add(jLabelFaixaInfeior);
        jLabelFaixaInfeior.setBounds(-320, 410, 1240, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Entrar.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(480, 270, 51, 30);

        jLabelLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/loguinfb.png"))); // NOI18N
        getContentPane().add(jLabelLogin);
        jLabelLogin.setBounds(230, 90, 320, 220);

        jLabelfundoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ameba2.png"))); // NOI18N
        getContentPane().add(jLabelfundoLogin);
        jLabelfundoLogin.setBounds(-20, -10, 790, 470);

        setSize(new java.awt.Dimension(775, 483));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        
        mod.setUsuario(jTextFieldUser.getText());
        mod.setSenha(jPasswordFieldSenha.getText());
        control.Salvar(mod);

        BeansLogin model = control.Pesquisar(mod);
        if(model.getPerfil().equals("ADMINISTRADOR") 
                && model.getUsuario().equals(jTextFieldUser.getText()) 
                && model.getSenha().equals(jPasswordFieldSenha.getText()) //&& model.getIp().equals("192.168.0.13")
                && jTextFieldUser.getText().length() > 0){
            
        visaoMaster.MenuPrincipal menu = new visaoMaster.MenuPrincipal(jTextFieldUser.getText());
        menu.setVisible(true);
        dispose();
        
        }if(model.getPerfil().equals("USUARIO") 
                && model.getUsuario().equals(jTextFieldUser.getText()) 
                && model.getSenha().equals(jPasswordFieldSenha.getText())
                && jTextFieldUser.getText().length() > 0){
        MenuPrincipal menu = new MenuPrincipal(jTextFieldUser.getText());
        menu.setVisible(true);
        dispose();
        }

      
        
        
       
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTextFieldUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUserActionPerformed

    private void jPasswordFieldSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldSenhaActionPerformed
/*
  public void login(){
    
        conex.conexao();
        try{
            conex.executaSql("select * from tbl_usuarios "); //where ativo=true
            conex.rs.first();
            if(jTextFieldUser.getText().equals(conex.rs.getString("usuario")) && jPasswordFieldSenha.getText().equals(conex.rs.getString("senha"))
            || jTextFieldUser.getText().equals("admin") && jPasswordFieldSenha.getText().equals("admin")){
                if(conex.rs.getString("perfil") == "ADMINISTRADOR"){

                MenuPrincipal menu = new MenuPrincipal();
                menu.setVisible(true);
                dispose();
                }
            }
            if(jTextFieldUser.getText().equals(conex.rs.getString("usuario")) && jPasswordFieldSenha.getText().equals(conex.rs.getString("senha"))){
               if(conex.rs.getString("perfil") == "USUARIO"){
                
                MenuPrincipalUsuario menu = new MenuPrincipalUsuario();
                menu.setVisible(true);
                dispose();    
               }
            } else{
                JOptionPane.showMessageDialog(rootPane, "Usuário ou Senha Incoreto");
            }
 
        }catch(SQLException ex){
                
        }
        conex.desconecta();

    }
  */        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFaixaInfeior;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelNameSetor;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabelfundoLogin;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}

 //Funcional com insert into no banco
/*   
 public void login2(){
    
        conex.conexao();
        try{
            conex.executaSql("select usuario, senha from tbl_usuarios "); //where ativo=true
            conex.rs.first();
            if(jTextFieldUser.getText().equals(conex.rs.getString("usuario")) || jTextFieldUser.getText().equals("admin")
                && jPasswordFieldSenha.getText().equals(conex.rs.getString("senha")) || jPasswordFieldSenha.getText().equals("admin")){

                MenuPrincipal menu = new MenuPrincipal();
                menu.setVisible(true);
                dispose();
            } else{
                JOptionPane.showMessageDialog(rootPane, "Usuário ou Senha Incoreto");
            }

        }catch(SQLException ex){
                
        }
        conex.desconecta();

    }*/