/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visaoMaster;

//import visaoUsuario.MenuPrincipal;
import modeloConection.ConexaoBD;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Beans.BeansLogin;
import Dao.DaoLogin;


/**
 *
 * @author Professor
 */
public class MenuPrincipal extends javax.swing.JFrame {

    ConexaoBD conecta = new ConexaoBD();
    BeansLogin mod = new BeansLogin();
    DaoLogin control = new DaoLogin();
    
    
    public MenuPrincipal(String usuario) {
        initComponents();
        conecta.conexao();
        
        jTextFieldUser.setText(usuario);
        
            mod.setUsuario(jTextFieldUser.getText());
            BeansLogin model = control.PesquisarUsuario(mod);
            jTextFieldNomeUser.setText("-"+model.getNome());
            
        
       // BeansLogin model = control.Pesquisar(mod);
       // jTextFieldUser.setText(model.getUsuario());
        
        
    }

    /*MenuPrincipal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }*/

    private MenuPrincipal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNameInst = new javax.swing.JLabel();
        jLabelNameSetor = new javax.swing.JLabel();
        jLabelAlterSenha = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jTextFieldNomeUser = new javax.swing.JTextField();
        jButtonSairAmeba = new javax.swing.JButton();
        jButtonCadastros = new javax.swing.JButton();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonRel = new javax.swing.JButton();
        jButtonTabAux = new javax.swing.JButton();
        jComboBoxAcesoRapido = new javax.swing.JComboBox<>();
        jLabelRegMov = new javax.swing.JLabel();
        jLabelCad = new javax.swing.JLabel();
        jLabelRel = new javax.swing.JLabel();
        jLabelPain = new javax.swing.JLabel();
        jLabelExit = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();
        jLabelFaixaInfeior = new javax.swing.JLabel();
        jLabelFaixaSuperior = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("SISOP - Sistema de Orçamento Pessoal");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelNameInst.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelNameInst.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNameInst.setText("SISOP - SISTEMA DE ORÇAMENTO PESSOAL ");
        getContentPane().add(jLabelNameInst);
        jLabelNameInst.setBounds(490, 20, 410, 30);

        jLabelNameSetor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelNameSetor.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNameSetor.setText("Núcleo de Tecnologia da Informação");
        getContentPane().add(jLabelNameSetor);
        jLabelNameSetor.setBounds(1060, 650, 260, 40);

        jLabelAlterSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/altSenha.png"))); // NOI18N
        jLabelAlterSenha.setToolTipText("Clique aqui para alterar sua senha");
        jLabelAlterSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAlterSenhaMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelAlterSenha);
        jLabelAlterSenha.setBounds(1330, 660, 23, 23);

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 102, 51));
        jLabelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelUsuario.setText("USUÁRIO:");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(590, 650, 70, 20);

        jTextFieldUser.setEditable(false);
        jTextFieldUser.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldUser.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextFieldUser.setForeground(new java.awt.Color(255, 102, 51));
        jTextFieldUser.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldUser.setBorder(null);
        getContentPane().add(jTextFieldUser);
        jTextFieldUser.setBounds(650, 650, 60, 20);

        jTextFieldNomeUser.setEditable(false);
        jTextFieldNomeUser.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNomeUser.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextFieldNomeUser.setForeground(new java.awt.Color(255, 102, 51));
        jTextFieldNomeUser.setBorder(null);
        getContentPane().add(jTextFieldNomeUser);
        jTextFieldNomeUser.setBounds(710, 650, 140, 20);

        jButtonSairAmeba.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSairAmeba.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonSairAmeba.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSairAmeba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/5_shutdown-128.png"))); // NOI18N
        jButtonSairAmeba.setToolTipText("Sair do Sistema");
        jButtonSairAmeba.setBorder(null);
        jButtonSairAmeba.setBorderPainted(false);
        jButtonSairAmeba.setContentAreaFilled(false);
        jButtonSairAmeba.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSairAmeba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSairAmebaMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonSairAmeba);
        jButtonSairAmeba.setBounds(980, 150, 180, 140);

        jButtonCadastros.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCadastros.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonCadastros.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/2_Misc_icon_Login_Manager_1785.png"))); // NOI18N
        jButtonCadastros.setToolTipText("Cadastros");
        jButtonCadastros.setBorder(null);
        jButtonCadastros.setBorderPainted(false);
        jButtonCadastros.setContentAreaFilled(false);
        jButtonCadastros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCadastros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCadastrosMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonCadastros);
        jButtonCadastros.setBounds(350, 150, 180, 140);

        jButtonRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRegistrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1_Money_Calculator.png"))); // NOI18N
        jButtonRegistrar.setToolTipText("Registrar Movimentos");
        jButtonRegistrar.setBorder(null);
        jButtonRegistrar.setBorderPainted(false);
        jButtonRegistrar.setContentAreaFilled(false);
        jButtonRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRegistrarMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonRegistrar);
        jButtonRegistrar.setBounds(150, 150, 180, 140);

        jButtonRel.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonRel.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/2_Misc_icon_My_Documents44_1827.jpg.png"))); // NOI18N
        jButtonRel.setToolTipText("Relatórios");
        jButtonRel.setBorder(null);
        jButtonRel.setBorderPainted(false);
        jButtonRel.setContentAreaFilled(false);
        jButtonRel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRelMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonRel);
        jButtonRel.setBounds(560, 150, 180, 140);

        jButtonTabAux.setBackground(new java.awt.Color(255, 255, 255));
        jButtonTabAux.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonTabAux.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTabAux.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3_Control Panel.png"))); // NOI18N
        jButtonTabAux.setToolTipText("Painel de Controle");
        jButtonTabAux.setBorder(null);
        jButtonTabAux.setBorderPainted(false);
        jButtonTabAux.setContentAreaFilled(false);
        jButtonTabAux.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonTabAux.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonTabAuxMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonTabAux);
        jButtonTabAux.setBounds(770, 150, 180, 140);

        jComboBoxAcesoRapido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBoxAcesoRapido.setMaximumRowCount(24);
        jComboBoxAcesoRapido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alterar Senha", "Destinos", "Marca", "Modelo", "Motorista", "Registro de Atividadedes", "Rel. Registro por Atividade", "Rel. Registro por Motorista", "Rel. Registro por Setor", "Rel. Registro por Veículo", "Tipo de Atividade", "Usuários", "Veículo" }));
        jComboBoxAcesoRapido.setName(""); // NOI18N
        jComboBoxAcesoRapido.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxAcesoRapidoItemStateChanged(evt);
            }
        });
        jComboBoxAcesoRapido.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jComboBoxAcesoRapidoCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jComboBoxAcesoRapido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAcesoRapidoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxAcesoRapido);
        jComboBoxAcesoRapido.setBounds(1170, 0, 160, 25);

        jLabelRegMov.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelRegMov.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRegMov.setText("Registrar Movimento");
        jLabelRegMov.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelRegMovMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelRegMov);
        jLabelRegMov.setBounds(150, 290, 180, 30);

        jLabelCad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCad.setText("Cadastros");
        jLabelCad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCadMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelCad);
        jLabelCad.setBounds(350, 290, 180, 30);

        jLabelRel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelRel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRel.setText("Relatórios");
        getContentPane().add(jLabelRel);
        jLabelRel.setBounds(560, 290, 180, 30);

        jLabelPain.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelPain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPain.setText("Painel de Controle");
        jLabelPain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPainMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelPain);
        jLabelPain.setBounds(770, 290, 180, 30);

        jLabelExit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelExit.setText("Sair");
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelExit);
        jLabelExit.setBounds(980, 290, 180, 30);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.gif"))); // NOI18N
        jButtonSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSairMouseClicked(evt);
            }
        });
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(1340, 0, 20, 20);

        jLabelFaixaInfeior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_FaixaInferior.png"))); // NOI18N
        getContentPane().add(jLabelFaixaInfeior);
        jLabelFaixaInfeior.setBounds(0, 650, 1690, 60);

        jLabelFaixaSuperior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_Faixa.png"))); // NOI18N
        getContentPane().add(jLabelFaixaSuperior);
        jLabelFaixaSuperior.setBounds(-40, 0, 1420, 60);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_fundo.png"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 20, 1420, 740);

        setSize(new java.awt.Dimension(1372, 729));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSairMouseClicked
                                           
    // TODO add your handling code here:

    int Confirm = JOptionPane.showConfirmDialog(null,"Sair do sistema?"," SISOP", JOptionPane.YES_NO_OPTION);
    if (Confirm == JOptionPane.YES_OPTION) {
        //JOptionPane.showMessageDialog(null, "Até breve ");
        conecta.desconecta();
        //Login login = new Login();
        //login.setVisible(true);
        dispose();
        //System.exit(0);
    } else if (Confirm == JOptionPane.NO_OPTION){
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }


    }//GEN-LAST:event_jButtonSairMouseClicked

    private void jComboBoxAcesoRapidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAcesoRapidoActionPerformed
      /*  
       
        if(jComboBoxAcesoRapido.getSelectedItem().equals("Marca")){
        TbMes marca = new TbMes();
        marca.setVisible(true);
        }
       if(jComboBoxAcesoRapido.getSelectedItem().equals("Modelo")){
        CadFonte modelo = new CadFonte();
        modelo.setVisible(true);
        }
       if(jComboBoxAcesoRapido.getSelectedItem().equals("Motorista")){
        CadMotorista cadm = new CadMotorista();
        cadm.setVisible(true);
        }
       if(jComboBoxAcesoRapido.getSelectedItem().equals("Registro de Atividadedes")){
        RegistrarAtiv reg = new RegistrarAtiv();
        reg.setVisible(true);
        }
       if(jComboBoxAcesoRapido.getSelectedItem().equals("Tipo de Atividade")){
        TbTipoAtividade tb = new TbTipoAtividade();
        tb.setVisible(true);
        }
       if(jComboBoxAcesoRapido.getSelectedItem().equals("Veículo")){
        CadVeiculos cadv = new CadVeiculos();
        cadv.setVisible(true);
        }
       if(jComboBoxAcesoRapido.getSelectedItem().equals("Destinos")){
        TbDestinos tbd = new TbDestinos();
        tbd.setVisible(true);
        }
       if(jComboBoxAcesoRapido.getSelectedItem().equals("Usuários")){
        CadUsuarios cdu = new CadUsuarios();
        cdu.setVisible(true);
        }
       if(jComboBoxAcesoRapido.getSelectedItem().equals("Alterar Senha")){
        AlterarSenha alts = new AlterarSenha(jTextFieldUser.getText());
        alts.setVisible(true);
        }
       if(jComboBoxAcesoRapido.getSelectedItem().equals("Rel. Registro por Atividade")){
        RelRegPorAtividade rela = new RelRegPorAtividade();
        rela.setVisible(true);
        }
       if(jComboBoxAcesoRapido.getSelectedItem().equals("Rel. Registro por Motorista")){
        RelRegPorMotorista relm = new RelRegPorMotorista();
        relm.setVisible(true);
        }
       if(jComboBoxAcesoRapido.getSelectedItem().equals("Rel. Registro por Placa")){
        RelRegPorVeiculo relp = new RelRegPorVeiculo();
        relp.setVisible(true);
        }
       if(jComboBoxAcesoRapido.getSelectedItem().equals("Rel. Registro por Setor")){
        RelRegPorSetor rels = new RelRegPorSetor();
        rels.setVisible(true);
        }
*/

        

    }//GEN-LAST:event_jComboBoxAcesoRapidoActionPerformed
    
    private void jButtonCadastrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCadastrosMouseClicked
        TbCadastros cad = new TbCadastros();
        cad.setVisible(true);
        
    }//GEN-LAST:event_jButtonCadastrosMouseClicked

    private void jButtonRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRegistrarMouseClicked
        RegMov reg = new RegMov();
        reg.setVisible(true);
        
    }//GEN-LAST:event_jButtonRegistrarMouseClicked

    private void jComboBoxAcesoRapidoCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jComboBoxAcesoRapidoCaretPositionChanged
        
    }//GEN-LAST:event_jComboBoxAcesoRapidoCaretPositionChanged

    private void jComboBoxAcesoRapidoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxAcesoRapidoItemStateChanged

    }//GEN-LAST:event_jComboBoxAcesoRapidoItemStateChanged

    private void jLabelAlterSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAlterSenhaMouseClicked
        AlterarSenha altsenha = new AlterarSenha(jTextFieldUser.getText());
        altsenha.setVisible(true);
    }//GEN-LAST:event_jLabelAlterSenhaMouseClicked

    private void jLabelRegMovMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelRegMovMouseClicked
        RegMov reg = new RegMov();
        reg.setVisible(true);
    }//GEN-LAST:event_jLabelRegMovMouseClicked

    private void jLabelCadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCadMouseClicked
         TbCadastros cad = new TbCadastros();
        cad.setVisible(true);
    }//GEN-LAST:event_jLabelCadMouseClicked

    private void jButtonRelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRelMouseClicked
        RelARelatorios rel = new RelARelatorios();
        rel.setVisible(true);
    }//GEN-LAST:event_jButtonRelMouseClicked

    private void jButtonTabAuxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTabAuxMouseClicked
        TbPanelControl selecTab = new TbPanelControl();
      selecTab.setVisible(true);
    }//GEN-LAST:event_jButtonTabAuxMouseClicked

    private void jLabelPainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPainMouseClicked
        TbPanelControl selecTab = new TbPanelControl();
      selecTab.setVisible(true);
    }//GEN-LAST:event_jLabelPainMouseClicked

    private void jButtonSairAmebaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSairAmebaMouseClicked
        int Confirm = JOptionPane.showConfirmDialog(null,"Sair do sistema?"," SISOP", JOptionPane.YES_NO_OPTION);
            if (Confirm == JOptionPane.YES_OPTION) {
            //JOptionPane.showMessageDialog(null, " Até breve ");
            conecta.desconecta();
            //Login login = new Login();
            //login.setVisible(true);
            dispose();
            
            //System.exit(0);
            } else if (Confirm == JOptionPane.NO_OPTION){
                setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButtonSairAmebaMouseClicked
    }
    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
        int Confirm = JOptionPane.showConfirmDialog(null,"Sair do sistema?"," SISOP", JOptionPane.YES_NO_OPTION);
            if (Confirm == JOptionPane.YES_OPTION) {
            //JOptionPane.showMessageDialog(null, " Até breve ");
            conecta.desconecta();
            //Login login = new Login();
            //login.setVisible(true);
            dispose();
            
            //System.exit(0);
            } else if (Confirm == JOptionPane.NO_OPTION){
                setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            }
    }//GEN-LAST:event_jLabelExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastros;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JButton jButtonRel;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSairAmeba;
    private javax.swing.JButton jButtonTabAux;
    private javax.swing.JComboBox<String> jComboBoxAcesoRapido;
    private javax.swing.JLabel jLabelAlterSenha;
    private javax.swing.JLabel jLabelCad;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelFaixaInfeior;
    private javax.swing.JLabel jLabelFaixaSuperior;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelNameInst;
    private javax.swing.JLabel jLabelNameSetor;
    private javax.swing.JLabel jLabelPain;
    private javax.swing.JLabel jLabelRegMov;
    private javax.swing.JLabel jLabelRel;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JTextField jTextFieldNomeUser;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
