/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visaoMaster;

import Beans.BeansDetalhamento;
import Beans.BeansRegistrarMov;
import Beans.BeansTabelas;
import Dao.DaoDetalhamento;
import Dao.DaoRegMov;
import controller.UpperCase;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import modeloConection.ConexaoBD;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Professor
 */
public class RegMov extends javax.swing.JFrame {
    ConexaoBD conex = new ConexaoBD();
    BeansRegistrarMov mod = new BeansRegistrarMov();
    DaoRegMov control = new DaoRegMov(); 
    BeansDetalhamento modDet = new BeansDetalhamento();
    DaoDetalhamento controlDet = new DaoDetalhamento();
       
    
    int flag=0;
    int limite=8;
    /**
     * Creates new form janelaPadrao
     */
    public RegMov() {
        initComponents();

        PreencherTabela("select a.id_regmov, a.mes, b.descricaotipo, a.detalhamento, a.valor from tbl_regmov as a inner join tbl_roots as b "
                + "on (a.id_tipo = b.id_tipo)"
                + "order by id_regmov desc");
        jTextFieldDetalhamento.setDocument(new UpperCase());
        jInternalFrameDetalhamento.setVisible(false);
        
        jTableRegMovimentos.setSelectionBackground(Color.blue);
        
        
        
        
        
        //("SELECT SUM(valor) FROM tbl_regmov WHERE tipo='GASTO'");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameDetalhamento = new javax.swing.JInternalFrame();
        jScrollPaneDetalhamento = new javax.swing.JScrollPane();
        jTableBuscaDetalhamento = new javax.swing.JTable();
        jButtonSairIF1 = new javax.swing.JButton();
        jLabelFaixaMenu2 = new javax.swing.JLabel();
        JlabelFundoMenuIF1 = new javax.swing.JLabel();
        jScrollPaneMovimentos = new javax.swing.JScrollPane();
        jTableRegMovimentos = new javax.swing.JTable();
        jLabelCod = new javax.swing.JLabel();
        jTextFieldCod = new javax.swing.JTextField();
        jLabelAno = new javax.swing.JLabel();
        jTextFieldAno = new javax.swing.JTextField();
        jLabelMes = new javax.swing.JLabel();
        jComboBoxMes = new javax.swing.JComboBox();
        jLabelTipo = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox();
        jLabelDescricao = new javax.swing.JLabel();
        jComboBoxDescricao = new javax.swing.JComboBox();
        jLabelDetObr = new javax.swing.JLabel();
        jLabelDetalhamento = new javax.swing.JLabel();
        jTextFieldDetalhamento = new javax.swing.JTextField();
        jButtonBuscarDet = new javax.swing.JButton();
        jButtonSalvaDetalhamento = new javax.swing.JButton();
        jLabelObrValor = new javax.swing.JLabel();
        jLabelValor = new javax.swing.JLabel();
        jTextFieldValor = new javax.swing.JTextField();
        jButtonIncluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonApagar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonImprimir = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelFaixaMenu = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Movimento");
        setResizable(false);
        getContentPane().setLayout(null);

        jInternalFrameDetalhamento.setTitle("Selecione um item");
        jInternalFrameDetalhamento.setVisible(true);
        jInternalFrameDetalhamento.getContentPane().setLayout(null);

        jTableBuscaDetalhamento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableBuscaDetalhamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableBuscaDetalhamento.setGridColor(new java.awt.Color(255, 255, 255));
        jTableBuscaDetalhamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBuscaDetalhamentoMouseClicked(evt);
            }
        });
        jScrollPaneDetalhamento.setViewportView(jTableBuscaDetalhamento);

        jInternalFrameDetalhamento.getContentPane().add(jScrollPaneDetalhamento);
        jScrollPaneDetalhamento.setBounds(0, 30, 450, 180);

        jButtonSairIF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/sair.png"))); // NOI18N
        jButtonSairIF1.setToolTipText("Sair");
        jButtonSairIF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairIF1ActionPerformed(evt);
            }
        });
        jInternalFrameDetalhamento.getContentPane().add(jButtonSairIF1);
        jButtonSairIF1.setBounds(400, 0, 45, 30);

        jLabelFaixaMenu2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFaixaMenu2.setForeground(new java.awt.Color(102, 255, 255));
        jLabelFaixaMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_Faixa.png"))); // NOI18N
        jInternalFrameDetalhamento.getContentPane().add(jLabelFaixaMenu2);
        jLabelFaixaMenu2.setBounds(0, 0, 770, 30);

        JlabelFundoMenuIF1.setBackground(new java.awt.Color(255, 255, 255));
        JlabelFundoMenuIF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_fundo.png"))); // NOI18N
        JlabelFundoMenuIF1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jInternalFrameDetalhamento.getContentPane().add(JlabelFundoMenuIF1);
        JlabelFundoMenuIF1.setBounds(-10, 10, 490, 220);

        getContentPane().add(jInternalFrameDetalhamento);
        jInternalFrameDetalhamento.setBounds(230, 30, 460, 240);

        jTableRegMovimentos.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jTableRegMovimentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableRegMovimentos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTableRegMovimentos.setGridColor(new java.awt.Color(255, 255, 255));
        jTableRegMovimentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRegMovimentosMouseClicked(evt);
            }
        });
        jScrollPaneMovimentos.setViewportView(jTableRegMovimentos);

        getContentPane().add(jScrollPaneMovimentos);
        jScrollPaneMovimentos.setBounds(400, 40, 510, 230);

        jLabelCod.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelCod.setText("Código:");
        getContentPane().add(jLabelCod);
        jLabelCod.setBounds(20, 40, 70, 30);

        jTextFieldCod.setEditable(false);
        jTextFieldCod.setEnabled(false);
        getContentPane().add(jTextFieldCod);
        jTextFieldCod.setBounds(90, 40, 50, 30);

        jLabelAno.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelAno.setText("Ano:");
        getContentPane().add(jLabelAno);
        jLabelAno.setBounds(270, 40, 50, 30);

        jTextFieldAno.setEditable(false);
        jTextFieldAno.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldAno.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextFieldAno.setText("2017");
        jTextFieldAno.setMaximumSize(new java.awt.Dimension(8, 8));
        getContentPane().add(jTextFieldAno);
        jTextFieldAno.setBounds(320, 40, 60, 30);

        jLabelMes.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelMes.setText("Mês:");
        getContentPane().add(jLabelMes);
        jLabelMes.setBounds(30, 80, 60, 30);

        jComboBoxMes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECIONE", "JANEIRO", "FEVEREIRO", "MARÇO", "ABRIL", "MAIO", "JUNHO", "JULHO", "AGOSTO", "SETEMBRO", "OUTUBRO", "NOVEMBRO", "DEZEMBRO" }));
        jComboBoxMes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMesItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBoxMes);
        jComboBoxMes.setBounds(90, 80, 290, 30);

        jLabelTipo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelTipo.setText("Tipo:");
        getContentPane().add(jLabelTipo);
        jLabelTipo.setBounds(30, 120, 60, 30);

        jComboBoxTipo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECIONE", "GASTO", "RENDA" }));
        jComboBoxTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTipoItemStateChanged(evt);
            }
        });
        jComboBoxTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxTipoMouseClicked(evt);
            }
        });
        getContentPane().add(jComboBoxTipo);
        jComboBoxTipo.setBounds(90, 120, 290, 30);

        jLabelDescricao.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelDescricao.setText("Descrição:");
        getContentPane().add(jLabelDescricao);
        jLabelDescricao.setBounds(30, 160, 60, 30);

        jComboBoxDescricao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxDescricao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECIONE" }));
        jComboBoxDescricao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxDescricaoMouseClicked(evt);
            }
        });
        getContentPane().add(jComboBoxDescricao);
        jComboBoxDescricao.setBounds(90, 160, 290, 30);

        jLabelDetObr.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelDetObr.setForeground(new java.awt.Color(255, 0, 0));
        jLabelDetObr.setText(" *");
        getContentPane().add(jLabelDetObr);
        jLabelDetObr.setBounds(0, 200, 30, 30);

        jLabelDetalhamento.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelDetalhamento.setText("Detalhamento:");
        getContentPane().add(jLabelDetalhamento);
        jLabelDetalhamento.setBounds(-20, 200, 110, 30);

        jTextFieldDetalhamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextFieldDetalhamento);
        jTextFieldDetalhamento.setBounds(90, 200, 230, 30);

        jButtonBuscarDet.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBuscarDet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/imgBuscar.png"))); // NOI18N
        jButtonBuscarDet.setToolTipText("Destinos Salvos");
        jButtonBuscarDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarDetActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscarDet);
        jButtonBuscarDet.setBounds(320, 200, 30, 30);

        jButtonSalvaDetalhamento.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalvaDetalhamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvarMenor.png"))); // NOI18N
        jButtonSalvaDetalhamento.setToolTipText("Salvar Destino");
        jButtonSalvaDetalhamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvaDetalhamentoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvaDetalhamento);
        jButtonSalvaDetalhamento.setBounds(350, 200, 30, 30);

        jLabelObrValor.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabelObrValor.setForeground(new java.awt.Color(255, 0, 0));
        jLabelObrValor.setText("  *");
        getContentPane().add(jLabelObrValor);
        jLabelObrValor.setBounds(10, 240, 20, 30);

        jLabelValor.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelValor.setText("Valor R$:");
        getContentPane().add(jLabelValor);
        jLabelValor.setBounds(10, 240, 80, 30);

        jTextFieldValor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(jTextFieldValor);
        jTextFieldValor.setBounds(90, 240, 70, 30);

        jButtonIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/incluir.png"))); // NOI18N
        jButtonIncluir.setToolTipText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIncluir);
        jButtonIncluir.setBounds(10, 0, 45, 30);

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/salvar.png"))); // NOI18N
        jButtonEditar.setToolTipText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEditar);
        jButtonEditar.setBounds(60, 0, 45, 30);

        jButtonApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/apagar.png"))); // NOI18N
        jButtonApagar.setToolTipText("Deletar");
        jButtonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonApagar);
        jButtonApagar.setBounds(110, 0, 45, 30);

        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/limpar.png"))); // NOI18N
        jButtonLimpar.setToolTipText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpar);
        jButtonLimpar.setBounds(160, 0, 45, 30);

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/pesquisar.png"))); // NOI18N
        jButtonPesquisar.setToolTipText("Buscar");
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(210, 0, 45, 30);

        jButtonImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/imprimir.png"))); // NOI18N
        jButtonImprimir.setToolTipText("Imprimir");
        jButtonImprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonImprimirMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonImprimir);
        jButtonImprimir.setBounds(260, 0, 45, 30);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/sair.png"))); // NOI18N
        jButtonSair.setToolTipText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(310, 0, 45, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("* Campos de preenchimento obrigatório.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 280, 220, 14);

        jLabelFaixaMenu.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFaixaMenu.setForeground(new java.awt.Color(102, 255, 255));
        jLabelFaixaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_Faixa.png"))); // NOI18N
        getContentPane().add(jLabelFaixaMenu);
        jLabelFaixaMenu.setBounds(0, 0, 930, 30);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_fundo.png"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 30, 920, 300);

        setSize(new java.awt.Dimension(924, 345));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        dispose(); 
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
    jTextFieldCod.setText("");
    jComboBoxMes.setSelectedItem(null);
    jComboBoxTipo.setSelectedItem(null);
    jComboBoxDescricao.setSelectedItem(null);
    jTextFieldDetalhamento.setText("");
    jTextFieldValor.setText("");
    jLabelObrValor.setVisible(false);
    
    jComboBoxDescricao.setSelectedItem("SELECIONE");
    jComboBoxMes.setSelectedItem("SELECIONE");
    jComboBoxTipo.setSelectedItem("SELECIONE");
    PreencherTabela("select a.id_regmov, a.mes, b.descricaotipo, a.detalhamento, a.valor from tbl_regmov as a inner join tbl_roots as b "
                + "on (a.id_tipo = b.id_tipo)"
                + "order by id_regmov desc");
        
        jButtonIncluir.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonApagar.setEnabled(false);
        
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        if(jTextFieldDetalhamento.getText().isEmpty()
               
        || jTextFieldValor.getText().isEmpty()
        ){
        
        if(jTextFieldValor.getText().isEmpty()){
        jLabelObrValor.setVisible(true);
        jTextFieldValor.requestFocus();
        }else{
        jLabelObrValor.setVisible(false);
        }
        

        if(jTextFieldDetalhamento.getText().isEmpty()){
        jLabelDetObr.setVisible(true);
        jTextFieldDetalhamento.requestFocus();
        }else{
        jLabelDetObr.setVisible(false);
        }
              
    }else{
        
    mod.setAno(Integer.parseInt(jTextFieldAno.getText()));
    mod.setMes((String) jComboBoxMes.getSelectedItem());
    mod.setTipo((String) jComboBoxTipo.getSelectedItem());
    mod.setDescricao((String)jComboBoxDescricao.getSelectedItem());
    mod.setDetalhamento(jTextFieldDetalhamento.getText());    
    mod.setValor(Double.parseDouble(jTextFieldValor.getText()));  

    control.Salvar(mod);
    //jButtonIncluir.setEnabled(false);
    jButtonEditar.setEnabled(true);
    jButtonApagar.setEnabled(true);
    }
    PreencherTabela("select a.id_regmov, a.mes, b.descricaotipo, a.detalhamento, a.valor from tbl_regmov as a inner join tbl_roots as b "
                + "on (a.id_tipo = b.id_tipo)"
                + "order by id_regmov desc");
          
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    private void jButtonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarActionPerformed
int Confirm = JOptionPane.showConfirmDialog(null,"Excluir registro?"," Excluir", JOptionPane.YES_NO_OPTION);
            if (Confirm == JOptionPane.YES_OPTION) {
            mod.setCodigo(Integer.parseInt(jTextFieldCod.getText()));
            control.Excluir(mod);
            
            PreencherTabela("select a.id_regmov, a.mes, b.descricaotipo, a.detalhamento, a.valor from tbl_regmov as a inner join tbl_roots as b "
                + "on (a.id_tipo = b.id_tipo)"
                + "order by id_regmov desc");
            
        
        jButtonEditar.setEnabled(false);
        jButtonApagar.setEnabled(false);
        jButtonIncluir.setEnabled(true);
        }else if (Confirm == JOptionPane.NO_OPTION){
                setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                }  
    }//GEN-LAST:event_jButtonApagarActionPerformed

    private void jButtonBuscarDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarDetActionPerformed
        PreencherTabelaDetalhamentoIF("select id_det, detalhamento from tbl_detdesc");
        jInternalFrameDetalhamento.setVisible(true);

    }//GEN-LAST:event_jButtonBuscarDetActionPerformed

    private void jButtonSalvaDetalhamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvaDetalhamentoActionPerformed
        if(jTextFieldDetalhamento.getText().isEmpty()){
            jTextFieldDetalhamento.requestFocus();
            jLabelDetObr.setVisible(true);
        }else{
            jLabelDetObr.setVisible(false);
            modDet.setDescricao(jTextFieldDetalhamento.getText());
            controlDet.Salvar(modDet);
        }
    }//GEN-LAST:event_jButtonSalvaDetalhamentoActionPerformed

    private void jComboBoxDescricaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxDescricaoMouseClicked
        if(jComboBoxTipo.getSelectedItem().equals("RENDA")){
            CbRenda();
           //PreencherTabelaDetalhamentoIFDescRenda("select id_descrenda, descricaorenda from tbl_descrend");
           //jInternalFrameDescricao.setVisible(true);             
        }       
        if(jComboBoxTipo.getSelectedItem().equals("GASTO")){
            CbGasto();
        //PreencherTabelaDetalhamentoIFDescGasto("select id_descgasto, descricaogasto from tbl_descgast");
        //jInternalFrameDescricao.setVisible(true);
        
        }if(jComboBoxTipo.getSelectedItem().equals("SELECIONE")){
        JOptionPane.showMessageDialog(null, "Selecione um tipo");
        jComboBoxTipo.requestFocus();
        }
    }//GEN-LAST:event_jComboBoxDescricaoMouseClicked

    private void jComboBoxTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxTipoMouseClicked
    
    }//GEN-LAST:event_jComboBoxTipoMouseClicked

    private void jTableRegMovimentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRegMovimentosMouseClicked
        String cod = ""+jTableRegMovimentos.getValueAt(jTableRegMovimentos.getSelectedRow(), 0);

        int i = Integer.parseInt(cod);
        
        mod.setCodigo(i); 
        BeansRegistrarMov model = control.PesquisarReg(mod);
        //control.PesquisarReg(mod);
        
            jTextFieldCod.setText(String.valueOf(model.getCodigo()));
            jTextFieldAno.setText(String.valueOf(model.getAno()));
            jComboBoxMes.setSelectedItem(model.getMes());
            jComboBoxTipo.setSelectedItem(model.getTipo());
            jComboBoxDescricao.setSelectedItem(model.getDescricao());
            jTextFieldDetalhamento.setText(model.getDetalhamento());
            jTextFieldValor.setText(String.valueOf(model.getValor()));
            
        jButtonIncluir.setEnabled(false);
        jButtonEditar.setEnabled(true);
        jButtonApagar.setEnabled(true);   
    }//GEN-LAST:event_jTableRegMovimentosMouseClicked

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
               if(jTextFieldDetalhamento.getText().isEmpty()
               
        || jTextFieldValor.getText().isEmpty()
        ){
        
        if(jTextFieldValor.getText().isEmpty()){
        jLabelObrValor.setVisible(true);
        jTextFieldValor.requestFocus();
        }else{
        jLabelObrValor.setVisible(false);
        }
        

        if(jTextFieldDetalhamento.getText().isEmpty()){
        jLabelDetObr.setVisible(true);
        jTextFieldDetalhamento.requestFocus();
        }else{
        jLabelDetObr.setVisible(false);
        }
              
    }else{
        
    mod.setAno(Integer.parseInt(jTextFieldAno.getText()));
    mod.setMes((String) jComboBoxMes.getSelectedItem());
    mod.setTipo((String) jComboBoxTipo.getSelectedItem());
    mod.setDescricao((String)jComboBoxDescricao.getSelectedItem());
    mod.setDetalhamento(jTextFieldDetalhamento.getText());    
    mod.setValor(Double.parseDouble(jTextFieldValor.getText()));  

    control.Editar(mod);
    jButtonIncluir.setEnabled(false);
    jButtonEditar.setEnabled(true);
    jButtonApagar.setEnabled(true);
    }
    PreencherTabela("select a.id_regmov, a.mes, b.descricaotipo, a.detalhamento, a.valor from tbl_regmov as a inner join tbl_roots as b "
                + "on (a.id_tipo = b.id_tipo)"
                + "order by id_regmov desc");
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonSairIF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairIF1ActionPerformed
        jInternalFrameDetalhamento.dispose();
    }//GEN-LAST:event_jButtonSairIF1ActionPerformed

    private void jTableBuscaDetalhamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBuscaDetalhamentoMouseClicked

        String desc = ""+jTableBuscaDetalhamento.getValueAt(jTableBuscaDetalhamento.getSelectedRow(), 1);
        modDet.setDescricao(desc); /*SETDETALHAMENTO*/
        controlDet.Pesquisar(modDet);
        jTextFieldDetalhamento.setText(modDet.getDescricao());
        jInternalFrameDetalhamento.dispose();
    }//GEN-LAST:event_jTableBuscaDetalhamentoMouseClicked

    private void jComboBoxMesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMesItemStateChanged
        PreencherTabela("select a.id_regmov, a.mes, b.descricaotipo, a.detalhamento, a.valor from tbl_regmov as a inner join tbl_roots as b "
                + "on (a.id_tipo = b.id_tipo)"
                + " where a.mes='"+ jComboBoxMes.getSelectedItem()+"'order by id_regmov desc");
    }//GEN-LAST:event_jComboBoxMesItemStateChanged

    private void jComboBoxTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTipoItemStateChanged
       PreencherTabela("select a.id_regmov, a.mes, a.tipo, b.descricaotipo, a.detalhamento, a.valor from tbl_regmov as a inner join tbl_roots as b "
                + "on (a.id_tipo = b.id_tipo)"
                + " where a.tipo='"+ jComboBoxTipo.getSelectedItem()+"' and a.mes='"+ jComboBoxMes.getSelectedItem()+"' order by id_regmov desc");
    }//GEN-LAST:event_jComboBoxTipoItemStateChanged

    private void jButtonImprimirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonImprimirMouseClicked
        if(jComboBoxMes.getSelectedItem().equals("SELECIONE") || jComboBoxTipo.getSelectedItem().equals("SELECIONE") ){
            if(jComboBoxMes.getSelectedItem().equals("SELECIONE")){
            JOptionPane.showMessageDialog(rootPane, "Selecione o mês");
            jComboBoxMes.setRequestFocusEnabled(true);
            }
            if(jComboBoxTipo.getSelectedItem().equals("SELECIONE")){
            JOptionPane.showMessageDialog(rootPane, "Selecione o tipo");
            jComboBoxTipo.setRequestFocusEnabled(true);
            }
        }else{
            String mes = (String) jComboBoxMes.getSelectedItem();
            String tipo = (String) jComboBoxTipo.getSelectedItem();
                
                try{
                    conex.executaSql("SELECT a.mes, b.periodo, b.descricaotipo, a.detalhamento, a.valor FROM tbl_regmov as a"
                    + " inner join tbl_roots as b on (a.id_tipo = b.id_tipo) WHERE a.tipo = '"+tipo+"' and a.mes = '"+mes+"'");
                    JRResultSetDataSource relatResul = new JRResultSetDataSource(conex.rs); // Paasando um resultset que ira servir como base de dados do relatório
                    JasperPrint jpPrint = JasperFillManager.fillReport("iReport/MovFinanceiras.jasper", new HashMap(), relatResul);// HashMap:Mapeamento do Diretório// relatResul: passa a base de dados que o rel sera preenchido
                    JasperViewer jv = new JasperViewer(jpPrint,false); //seta falso para exit_on_close
                    jv.setVisible(true);//chama para visualização
                    //jv.toFront();//caso o relatório saia atras do programa, este comando tras o relatório para frete da aplicação
                }
        
                catch (JRException ex) {
                   JOptionPane.showMessageDialog(rootPane, "Erro ao carregar relatório\nErro:"+ex); 
               }
             
                }
        
        // https://www.youtube.com/watch?v=niRVKJPfOJU 
    }//GEN-LAST:event_jButtonImprimirMouseClicked

    
    public void CbRenda(){
    
        conex.conexao();
        conex.executaSql("select *from tbl_roots where tipo = 'RENDA' order by descricaotipo ");
        try{
            conex.rs.first();
            jComboBoxDescricao.removeAllItems();
            do{
                jComboBoxDescricao.addItem(conex.rs.getString("descricaotipo").toUpperCase());
            }while(conex.rs.next());
        
        
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Registre as rendas nas tabelas auxiliares\n"+ex);
            //RegistrarAtiv.this.dispose();
            }
        }
    
    public void CbGasto(){
    
        conex.conexao();
        conex.executaSql("select *from tbl_roots where tipo = 'GASTO' order by descricaotipo ");
        try{
            conex.rs.first();
            jComboBoxDescricao.removeAllItems();
            do{
                jComboBoxDescricao.addItem(conex.rs.getString("descricaotipo").toUpperCase());
            }while(conex.rs.next());
        
        
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Registre os gasto nas tabelas auxiliares\n"+ex);
            //RegistrarAtiv.this.dispose();
            }
        }
    
    public void PreencherTabela(String SQL){
      ArrayList dados = new ArrayList();
      String[] colunas = new String[]{"","","","",""};
      
      conex.conexao();
      conex.executaSql(SQL);

      try{
          conex.rs.first();       
          do{
              dados.add(new Object[]{conex.rs.getInt("id_regmov"),
                                     conex.rs.getString("mes"),
                                     conex.rs.getString("descricaotipo"),                                     
                                     conex.rs.getString("detalhamento"),
                                     conex.rs.getDouble("valor")
                                     //conex.rs.getString("valor")
                                    });
 
          }while(conex.rs.next());
      
        }catch(SQLException ex){
 
           // JOptionPane.showMessageDialog(rootPane, "Não foram encontrados registros para os filtros selecionados!\nSelecione opção válida");
            
          //JOptionPane.showMessageDialog(rootPane, "Erro ao preencher ArrayList\nErro:"+ex); 
        }
      
      BeansTabelas modelo = new BeansTabelas(dados, colunas);
      
      jTableRegMovimentos.setModel(modelo);
      jTableRegMovimentos.getColumnModel().getColumn(0).setPreferredWidth(30);
      jTableRegMovimentos.getColumnModel().getColumn(0).setResizable(false);
      jTableRegMovimentos.getColumnModel().getColumn(0).setHeaderValue("ID");
      jTableRegMovimentos.getColumnModel().getColumn(1).setPreferredWidth(70);
      jTableRegMovimentos.getColumnModel().getColumn(1).setResizable(false);
      jTableRegMovimentos.getColumnModel().getColumn(1).setHeaderValue("MÊS");
      jTableRegMovimentos.getColumnModel().getColumn(2).setPreferredWidth(140);
      jTableRegMovimentos.getColumnModel().getColumn(2).setResizable(false); //não redimensionaveL
      jTableRegMovimentos.getColumnModel().getColumn(2).setHeaderValue("DESCRIÇÃO");
      jTableRegMovimentos.getColumnModel().getColumn(3).setPreferredWidth(197);
      jTableRegMovimentos.getColumnModel().getColumn(3).setResizable(false);
      jTableRegMovimentos.getColumnModel().getColumn(3).setHeaderValue("DETALHAMENTO");
      jTableRegMovimentos.getColumnModel().getColumn(4).setPreferredWidth(50);
      jTableRegMovimentos.getColumnModel().getColumn(4).setResizable(false);
      jTableRegMovimentos.getColumnModel().getColumn(4).setHeaderValue("VALOR");

      //jTableRegMovimentos.getTableHeader().setReorderingAllowed(false); //não reordenavel
      jTableRegMovimentos.setAutoResizeMode(jTableRegMovimentos.AUTO_RESIZE_OFF); //não redmencionar
      jTableRegMovimentos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//selicioar um dado por vez
    }
    

    
    public void PreencherTabelaDetalhamentoIF(String SQL){
      ArrayList dados = new ArrayList();
      String[] colunas = new String[]{"ID","DESCRIÇÃO"};
      
      conex.conexao();
      conex.executaSql(SQL);

      try{
          conex.rs.first();       
          do{
              dados.add(new Object[]{conex.rs.getString("id_det"),
                                     conex.rs.getString("detalhamento")
                                     
                                     
                                    });
 
          }while(conex.rs.next());
      
        }catch(SQLException ex){
          
          JOptionPane.showMessageDialog(rootPane, "Erro ao preencher ArrayList\nErro:"+ex);
        }
      
      BeansTabelas bv = new BeansTabelas(dados, colunas);
      
      jTableBuscaDetalhamento.setModel(bv);
      jTableBuscaDetalhamento.getColumnModel().getColumn(0).setPreferredWidth(30);
      jTableBuscaDetalhamento.getColumnModel().getColumn(0).setResizable(false);
      jTableBuscaDetalhamento.getColumnModel().getColumn(0).setHeaderValue("ID");
      jTableBuscaDetalhamento.getColumnModel().getColumn(1).setPreferredWidth(430);
      jTableBuscaDetalhamento.getColumnModel().getColumn(1).setResizable(false); //não redimensionaveL
      jTableBuscaDetalhamento.getColumnModel().getColumn(1).setHeaderValue("DESCRIÇÃO");
      
      

      jTableRegMovimentos.getTableHeader().setReorderingAllowed(false); //não reordenavel
    //jTableRegMovimentos.setAutoResizeMode(jTableBuscaDetalhamento.AUTO_RESIZE_OFF); //não redmencionar
      jTableRegMovimentos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);//selicioar um dado por vez
    }
    
    public void limparTabela() {
    while (jTableRegMovimentos.getRowCount() > 0) {
    DefaultTableModel dm = (DefaultTableModel) jTableRegMovimentos.getModel();
    dm.getDataVector().removeAllElements();
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPadrao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlabelFundoMenuIF1;
    private javax.swing.JButton jButtonApagar;
    private javax.swing.JButton jButtonBuscarDet;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonImprimir;
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSairIF1;
    private javax.swing.JButton jButtonSalvaDetalhamento;
    public javax.swing.JComboBox jComboBoxDescricao;
    private javax.swing.JComboBox jComboBoxMes;
    public javax.swing.JComboBox jComboBoxTipo;
    private javax.swing.JInternalFrame jInternalFrameDetalhamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAno;
    private javax.swing.JLabel jLabelCod;
    private javax.swing.JLabel jLabelDescricao;
    private javax.swing.JLabel jLabelDetObr;
    private javax.swing.JLabel jLabelDetalhamento;
    private javax.swing.JLabel jLabelFaixaMenu;
    private javax.swing.JLabel jLabelFaixaMenu2;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelMes;
    private javax.swing.JLabel jLabelObrValor;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JScrollPane jScrollPaneDetalhamento;
    private javax.swing.JScrollPane jScrollPaneMovimentos;
    private javax.swing.JTable jTableBuscaDetalhamento;
    private javax.swing.JTable jTableRegMovimentos;
    public javax.swing.JTextField jTextFieldAno;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldDetalhamento;
    private javax.swing.JTextField jTextFieldValor;
    // End of variables declaration//GEN-END:variables
}
