/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visaoMaster;

/**
 *
 * @author Professor
 */
public class RelARelatorios extends javax.swing.JFrame {

    /**
     * Creates new form janelaPadrao
     */
    public RelARelatorios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSair = new javax.swing.JButton();
        jButtonRelGasPorAno = new javax.swing.JButton();
        jButtonRelGastosPorPeriodo = new javax.swing.JButton();
        jButtonRelRendaPorAno = new javax.swing.JButton();
        jButtonRelRendaPorMes = new javax.swing.JButton();
        jButtonRelGastoERendaPorMes = new javax.swing.JButton();
        jButtonRelInvestiments = new javax.swing.JButton();
        jButtonRelInvestimentosPorMes = new javax.swing.JButton();
        jButtonRelGastosPorMes = new javax.swing.JButton();
        jButtonRelCorretistas = new javax.swing.JButton();
        jButtonRelContasBancarias = new javax.swing.JButton();
        jLabelAluno = new javax.swing.JLabel();
        jLabelFaixaMenu = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatórios");
        setResizable(false);
        getContentPane().setLayout(null);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/sair.png"))); // NOI18N
        jButtonSair.setToolTipText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(450, 0, 45, 30);

        jButtonRelGasPorAno.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRelGasPorAno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonRelGasPorAno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3_rel.png"))); // NOI18N
        jButtonRelGasPorAno.setText("GASTOS POR ANO");
        jButtonRelGasPorAno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonRelGasPorAno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRelGasPorAnoMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonRelGasPorAno);
        jButtonRelGasPorAno.setBounds(0, 40, 250, 25);

        jButtonRelGastosPorPeriodo.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRelGastosPorPeriodo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonRelGastosPorPeriodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3_rel.png"))); // NOI18N
        jButtonRelGastosPorPeriodo.setText("GASTOS POR MËS/PERÍODO");
        jButtonRelGastosPorPeriodo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonRelGastosPorPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelGastosPorPeriodoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRelGastosPorPeriodo);
        jButtonRelGastosPorPeriodo.setBounds(0, 100, 250, 25);

        jButtonRelRendaPorAno.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRelRendaPorAno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonRelRendaPorAno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3_rel.png"))); // NOI18N
        jButtonRelRendaPorAno.setText("RENDA POR ANO");
        jButtonRelRendaPorAno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonRelRendaPorAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelRendaPorAnoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRelRendaPorAno);
        jButtonRelRendaPorAno.setBounds(0, 130, 250, 25);

        jButtonRelRendaPorMes.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRelRendaPorMes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonRelRendaPorMes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3_rel.png"))); // NOI18N
        jButtonRelRendaPorMes.setText("RENDA POR MÊS");
        jButtonRelRendaPorMes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonRelRendaPorMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelRendaPorMesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRelRendaPorMes);
        jButtonRelRendaPorMes.setBounds(0, 160, 250, 25);

        jButtonRelGastoERendaPorMes.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRelGastoERendaPorMes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonRelGastoERendaPorMes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3_rel.png"))); // NOI18N
        jButtonRelGastoERendaPorMes.setText("GASTO E RENDA POR MÊS");
        jButtonRelGastoERendaPorMes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonRelGastoERendaPorMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelGastoERendaPorMesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRelGastoERendaPorMes);
        jButtonRelGastoERendaPorMes.setBounds(0, 190, 250, 25);

        jButtonRelInvestiments.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRelInvestiments.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonRelInvestiments.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3_rel.png"))); // NOI18N
        jButtonRelInvestiments.setText("INVESTIMENTOS POR ANO");
        jButtonRelInvestiments.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonRelInvestiments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelInvestimentsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRelInvestiments);
        jButtonRelInvestiments.setBounds(0, 220, 250, 25);

        jButtonRelInvestimentosPorMes.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRelInvestimentosPorMes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonRelInvestimentosPorMes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3_rel.png"))); // NOI18N
        jButtonRelInvestimentosPorMes.setText("INVESTIMESTOS POR MÊS");
        jButtonRelInvestimentosPorMes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonRelInvestimentosPorMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelInvestimentosPorMesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRelInvestimentosPorMes);
        jButtonRelInvestimentosPorMes.setBounds(0, 250, 250, 25);

        jButtonRelGastosPorMes.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRelGastosPorMes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonRelGastosPorMes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3_rel.png"))); // NOI18N
        jButtonRelGastosPorMes.setText("GASTOS POR MËS");
        jButtonRelGastosPorMes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonRelGastosPorMes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRelGastosPorMesMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonRelGastosPorMes);
        jButtonRelGastosPorMes.setBounds(0, 70, 250, 25);

        jButtonRelCorretistas.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRelCorretistas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonRelCorretistas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3_rel.png"))); // NOI18N
        jButtonRelCorretistas.setText("CORRETISTAS");
        jButtonRelCorretistas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonRelCorretistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelCorretistasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRelCorretistas);
        jButtonRelCorretistas.setBounds(0, 280, 250, 25);

        jButtonRelContasBancarias.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRelContasBancarias.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonRelContasBancarias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3_rel.png"))); // NOI18N
        jButtonRelContasBancarias.setText("CONTAS BANCÁRIAS");
        jButtonRelContasBancarias.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButtonRelContasBancarias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRelContasBancariasMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonRelContasBancarias);
        jButtonRelContasBancarias.setBounds(0, 310, 250, 25);

        jLabelAluno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/2_Misc_icon_My_Documents44_1827.jpg.png"))); // NOI18N
        getContentPane().add(jLabelAluno);
        jLabelAluno.setBounds(260, 60, 210, 230);

        jLabelFaixaMenu.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFaixaMenu.setForeground(new java.awt.Color(102, 255, 255));
        jLabelFaixaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_Faixa.png"))); // NOI18N
        getContentPane().add(jLabelFaixaMenu);
        jLabelFaixaMenu.setBounds(0, 0, 500, 30);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_fundo.png"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 30, 540, 320);

        setSize(new java.awt.Dimension(509, 386));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
    
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonRelInvestimentosPorMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelInvestimentosPorMesActionPerformed
        RelAplPorMes rel = new RelAplPorMes();
        rel.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonRelInvestimentosPorMesActionPerformed

    private void jButtonRelRendaPorMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelRendaPorMesActionPerformed
       RelRenPorMes rel = new RelRenPorMes();
       rel.setVisible(true);
       dispose();
        
    }//GEN-LAST:event_jButtonRelRendaPorMesActionPerformed

    private void jButtonRelInvestimentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelInvestimentsActionPerformed
       
        RelAplPorAno rel = new RelAplPorAno();
        rel.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonRelInvestimentsActionPerformed

    private void jButtonRelGastosPorPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelGastosPorPeriodoActionPerformed
        RelGasPorPeriodo rel = new RelGasPorPeriodo();
        rel.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonRelGastosPorPeriodoActionPerformed

    private void jButtonRelRendaPorAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelRendaPorAnoActionPerformed
        RelRenPorAno rel = new RelRenPorAno();
        rel.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonRelRendaPorAnoActionPerformed

    private void jButtonRelCorretistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelCorretistasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRelCorretistasActionPerformed

    private void jButtonRelGasPorAnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRelGasPorAnoMouseClicked
        RelGasPorAno rel = new RelGasPorAno();
        rel.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonRelGasPorAnoMouseClicked

    private void jButtonRelGastosPorMesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRelGastosPorMesMouseClicked
        RelGasPorMes rel = new RelGasPorMes();
        rel.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonRelGastosPorMesMouseClicked

    private void jButtonRelGastoERendaPorMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelGastoERendaPorMesActionPerformed
        RelGasRenPorMes rel = new RelGasRenPorMes();
        rel.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonRelGastoERendaPorMesActionPerformed

    private void jButtonRelContasBancariasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRelContasBancariasMouseClicked
        RelContasBancarias leite = new RelContasBancarias();
        leite.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonRelContasBancariasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelARelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelARelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelARelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelARelatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelARelatorios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRelContasBancarias;
    private javax.swing.JButton jButtonRelCorretistas;
    private javax.swing.JButton jButtonRelGasPorAno;
    private javax.swing.JButton jButtonRelGastoERendaPorMes;
    private javax.swing.JButton jButtonRelGastosPorMes;
    private javax.swing.JButton jButtonRelGastosPorPeriodo;
    private javax.swing.JButton jButtonRelInvestimentosPorMes;
    private javax.swing.JButton jButtonRelInvestiments;
    private javax.swing.JButton jButtonRelRendaPorAno;
    private javax.swing.JButton jButtonRelRendaPorMes;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelAluno;
    private javax.swing.JLabel jLabelFaixaMenu;
    private javax.swing.JLabel jLabelFundo;
    // End of variables declaration//GEN-END:variables
}
