/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visaoMaster;

import com.sun.org.apache.bcel.internal.generic.AALOAD;
import javax.swing.JOptionPane;

/**
 *
 * @author Professor
 */
public class TbCadastros extends javax.swing.JFrame {

    /**
     * Creates new form janelaPadrao
     */
    public TbCadastros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCadCre = new javax.swing.JLabel();
        jLabelCadCorDes = new javax.swing.JLabel();
        jLabelOpB = new javax.swing.JLabel();
        jLabelOpBdESC = new javax.swing.JLabel();
        jButtonSair = new javax.swing.JButton();
        jLabelFaixaMenu = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastros");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelCadCre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCadCre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCadCre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCadCre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/2_CadCorretista.png"))); // NOI18N
        jLabelCadCre.setToolTipText("Cadastrar Corretista");
        jLabelCadCre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelCadCre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCadCreMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelCadCre);
        jLabelCadCre.setBounds(120, 50, 130, 100);

        jLabelCadCorDes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCadCorDes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCadCorDes.setText("Cadastrar Corretista");
        getContentPane().add(jLabelCadCorDes);
        jLabelCadCorDes.setBounds(120, 140, 130, 30);

        jLabelOpB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelOpB.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOpB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOpB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/2_ContasBancarias..png"))); // NOI18N
        jLabelOpB.setToolTipText("Cadastrar Contas Bancárias");
        jLabelOpB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelOpB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelOpBMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelOpB);
        jLabelOpB.setBounds(260, 50, 130, 100);

        jLabelOpBdESC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelOpBdESC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOpBdESC.setText(" Contas Bancárias");
        getContentPane().add(jLabelOpBdESC);
        jLabelOpBdESC.setBounds(260, 140, 130, 30);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/sair.png"))); // NOI18N
        jButtonSair.setToolTipText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(450, 0, 45, 30);

        jLabelFaixaMenu.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFaixaMenu.setForeground(new java.awt.Color(102, 255, 255));
        jLabelFaixaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_Faixa.png"))); // NOI18N
        getContentPane().add(jLabelFaixaMenu);
        jLabelFaixaMenu.setBounds(0, 0, 500, 30);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_fundo.png"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 20, 500, 190);

        setSize(new java.awt.Dimension(505, 241));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jLabelCadCreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCadCreMouseClicked
        Corretista motorista = new Corretista();
        motorista.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelCadCreMouseClicked

    private void jLabelOpBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelOpBMouseClicked
      CadContasBancarias cont = new CadContasBancarias();
      cont.setVisible(true);
      dispose();
        
    }//GEN-LAST:event_jLabelOpBMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPadrao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelCadCorDes;
    private javax.swing.JLabel jLabelCadCre;
    private javax.swing.JLabel jLabelFaixaMenu;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelOpB;
    private javax.swing.JLabel jLabelOpBdESC;
    // End of variables declaration//GEN-END:variables
}
