/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visaoMaster;

/**
 *
 * @author Professor
 */
public class TbPanelControl extends javax.swing.JFrame {

    /**
     * Creates new form janelaPadrao
     */
    public TbPanelControl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCadCre = new javax.swing.JLabel();
        jLabelCadCorDes = new javax.swing.JLabel();
        jLabelOpB = new javax.swing.JLabel();
        jLabelOpBdESC = new javax.swing.JLabel();
        jButtonSair1 = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelFaixaMenu = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Painel de Controle");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelCadCre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCadCre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCadCre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCadCre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/3_Raizes.png"))); // NOI18N
        jLabelCadCre.setToolTipText("Cadastrar Tabelas");
        jLabelCadCre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelCadCre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCadCreMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelCadCre);
        jLabelCadCre.setBounds(120, 50, 130, 100);

        jLabelCadCorDes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCadCorDes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCadCorDes.setText("Tabelas");
        getContentPane().add(jLabelCadCorDes);
        jLabelCadCorDes.setBounds(120, 140, 130, 30);

        jLabelOpB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelOpB.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOpB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOpB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/2_CadCorretista.png"))); // NOI18N
        jLabelOpB.setToolTipText("Cadastrar Usuários");
        jLabelOpB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelOpB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelOpBMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelOpB);
        jLabelOpB.setBounds(260, 50, 130, 100);

        jLabelOpBdESC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelOpBdESC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelOpBdESC.setText("Usuários");
        getContentPane().add(jLabelOpBdESC);
        jLabelOpBdESC.setBounds(260, 140, 130, 30);

        jButtonSair1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/sair.png"))); // NOI18N
        jButtonSair1.setToolTipText("Sair");
        jButtonSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSair1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair1);
        jButtonSair1.setBounds(450, 0, 45, 30);

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/windows/sair.png"))); // NOI18N
        jButtonSair.setToolTipText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSair);
        jButtonSair.setBounds(520, 0, 45, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Selecione um menu");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 190, 120, 14);

        jLabelFaixaMenu.setBackground(new java.awt.Color(255, 255, 255));
        jLabelFaixaMenu.setForeground(new java.awt.Color(102, 255, 255));
        jLabelFaixaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_Faixa.png"))); // NOI18N
        getContentPane().add(jLabelFaixaMenu);
        jLabelFaixaMenu.setBounds(0, 0, 580, 30);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/menuprincipal_fundo.png"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 30, 580, 180);

        setSize(new java.awt.Dimension(505, 241));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
    dispose();        
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSair1ActionPerformed
        dispose();       
    }//GEN-LAST:event_jButtonSair1ActionPerformed

    private void jLabelCadCreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCadCreMouseClicked
        CadRoots roots = new CadRoots();
        roots.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelCadCreMouseClicked

    private void jLabelOpBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelOpBMouseClicked
        CadUsuarios user = new CadUsuarios();
        user.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelOpBMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPadrao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPadrao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSair1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCadCorDes;
    private javax.swing.JLabel jLabelCadCre;
    private javax.swing.JLabel jLabelFaixaMenu;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelOpB;
    private javax.swing.JLabel jLabelOpBdESC;
    // End of variables declaration//GEN-END:variables
}
